import 'package:crupierly/domain/enum/card_types.dart';
import 'package:crupierly/domain/models/card_value.dart';

const List<CardValue> orderedDeck = [
  //Hearts
  CardValue(cardType: CardType.heart, symbol: 'K', value: 13),
  CardValue(cardType: CardType.heart, symbol: 'Q', value: 12),
  CardValue(cardType: CardType.heart, symbol: 'J', value: 11),
  CardValue(cardType: CardType.heart, symbol: '10', value: 10),
  CardValue(cardType: CardType.heart, symbol: '9', value: 9),
  CardValue(cardType: CardType.heart, symbol: '8', value: 8),
  CardValue(cardType: CardType.heart, symbol: '7', value: 7),
  CardValue(cardType: CardType.heart, symbol: '6', value: 6),
  CardValue(cardType: CardType.heart, symbol: '5', value: 5),
  CardValue(cardType: CardType.heart, symbol: '4', value: 4),
  CardValue(cardType: CardType.heart, symbol: '3', value: 3),
  CardValue(cardType: CardType.heart, symbol: '2', value: 2),
  CardValue(cardType: CardType.heart, symbol: 'A', value: 1),
  // //Diamonds
  CardValue(cardType: CardType.diamond, symbol: 'K', value: 13),
  CardValue(cardType: CardType.diamond, symbol: 'Q', value: 12),
  CardValue(cardType: CardType.diamond, symbol: 'J', value: 11),
  CardValue(cardType: CardType.diamond, symbol: '10', value: 10),
  CardValue(cardType: CardType.diamond, symbol: '9', value: 9),
  CardValue(cardType: CardType.diamond, symbol: '8', value: 8),
  CardValue(cardType: CardType.diamond, symbol: '7', value: 7),
  CardValue(cardType: CardType.diamond, symbol: '6', value: 6),
  CardValue(cardType: CardType.diamond, symbol: '5', value: 5),
  CardValue(cardType: CardType.diamond, symbol: '4', value: 4),
  CardValue(cardType: CardType.diamond, symbol: '3', value: 3),
  CardValue(cardType: CardType.diamond, symbol: '2', value: 2),
  CardValue(cardType: CardType.diamond, symbol: 'A', value: 1),
  //Spades
  CardValue(cardType: CardType.spade, symbol: 'K', value: 13),
  CardValue(cardType: CardType.spade, symbol: 'Q', value: 12),
  CardValue(cardType: CardType.spade, symbol: 'J', value: 11),
  CardValue(cardType: CardType.spade, symbol: '10', value: 10),
  CardValue(cardType: CardType.spade, symbol: '9', value: 9),
  CardValue(cardType: CardType.spade, symbol: '8', value: 8),
  CardValue(cardType: CardType.spade, symbol: '7', value: 7),
  CardValue(cardType: CardType.spade, symbol: '6', value: 6),
  CardValue(cardType: CardType.spade, symbol: '5', value: 5),
  CardValue(cardType: CardType.spade, symbol: '4', value: 4),
  CardValue(cardType: CardType.spade, symbol: '3', value: 3),
  CardValue(cardType: CardType.spade, symbol: '2', value: 2),
  CardValue(cardType: CardType.spade, symbol: 'A', value: 1),
  //Clubs
  CardValue(cardType: CardType.club, symbol: 'K', value: 13),
  CardValue(cardType: CardType.club, symbol: 'Q', value: 12),
  CardValue(cardType: CardType.club, symbol: 'J', value: 11),
  CardValue(cardType: CardType.club, symbol: '10', value: 10),
  CardValue(cardType: CardType.club, symbol: '9', value: 9),
  CardValue(cardType: CardType.club, symbol: '8', value: 8),
  CardValue(cardType: CardType.club, symbol: '7', value: 7),
  CardValue(cardType: CardType.club, symbol: '6', value: 6),
  CardValue(cardType: CardType.club, symbol: '5', value: 5),
  CardValue(cardType: CardType.club, symbol: '4', value: 4),
  CardValue(cardType: CardType.club, symbol: '3', value: 3),
  CardValue(cardType: CardType.club, symbol: '2', value: 2),
  CardValue(cardType: CardType.club, symbol: 'A', value: 1),
];
